services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: employee_data
      POSTGRES_USER: employee_data
      POSTGRES_PASSWORD: employee_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
