spring.application.name=employee-data-management

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_data
spring.datasource.username=employee_data
spring.datasource.password=employee_data

spring.jpa.hibernate.ddl-auto=validate

app.encryption.key=${APP_ENCRYPTION_KEY}
app.api-key=${APP_API_KEY}
